version: '3.8'

services:
  db:
    image: postgres:15
    container_name: whisper-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: whispersales
      POSTGRES_PASSWORD: whispersales
      POSTGRES_DB: whispersales
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    container_name: whisper-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: redis-server --appendonly yes

volumes:
  pgdata:
  redisdata: 