"""update account status and user role enums

Revision ID: f3b140dcf8f2
Revises: 4e4f7cda0068
Create Date: 2024-03-29 16:38:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3b140dcf8f2'
down_revision: Union[str, None] = '4e4f7cda0068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Handle accountstatus enum
    op.execute('ALTER TYPE accountstatus RENAME TO accountstatus_old')
    op.execute("CREATE TYPE accountstatus AS ENUM ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'DELETED')")
    op.execute('ALTER TABLE users ALTER COLUMN account_status TYPE accountstatus USING account_status::text::accountstatus')
    op.execute('DROP TYPE accountstatus_old')

    # Handle userrole enum
    op.execute('ALTER TYPE userrole RENAME TO userrole_old')
    op.execute("CREATE TYPE userrole AS ENUM ('FREE', 'PRO', 'ADMIN', 'USER', 'MANAGER')")
    op.execute('ALTER TABLE users ALTER COLUMN role TYPE userrole USING role::text::userrole')
    op.execute('DROP TYPE userrole_old')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Handle accountstatus enum
    op.execute('ALTER TYPE accountstatus RENAME TO accountstatus_old')
    op.execute("CREATE TYPE accountstatus AS ENUM ('active', 'inactive', 'suspended', 'deleted')")
    op.execute('ALTER TABLE users ALTER COLUMN account_status TYPE accountstatus USING account_status::text::accountstatus')
    op.execute('DROP TYPE accountstatus_old')

    # Handle userrole enum
    op.execute('ALTER TYPE userrole RENAME TO userrole_old')
    op.execute("CREATE TYPE userrole AS ENUM ('free', 'pro', 'admin', 'user', 'manager')")
    op.execute('ALTER TABLE users ALTER COLUMN role TYPE userrole USING role::text::userrole')
    op.execute('DROP TYPE userrole_old')
    # ### end Alembic commands ### 